DB_IP: 127.0.0.1
DB_PORT: 5432
DB_DATABASE_NAME: library_book
DB_URL: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_DATABASE_NAME}
DB_USERNAME: postgres
DB_PASSWORD: postgres
DB_SCHEMA: public


server:
  port: 8089
  #Всегда включать текст ошибки в Response
  # (когда сервер транслирует ошибку для клиента)
  error:
    include-message: always

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    create-schemas: true
    default-schema: ${DB_SCHEMA}


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          # Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
          lob.non_contextual_creation: true
          time_zone: UTC
          # to avoid name conflict of custom table objects
          # with object names in PostgresSQL
      auto_quote_keyword: true

management:
  endpoint:
    gateway:
      enabled: true # включаем Actuator
  endpoints:
    web:
      exposure:
        include: "*" #указываем, что нужно включить все endpoints of the Actuator

logging:
  pattern:
    # определяем формат более короткого отображение логов
    console: '%C{1.yaml.} [%-5level] %d{HH:mm:ss} - %msg%n'

  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

      springframework:
        web:
          client: trace