spring:
  application:
    name: spring-config-server-github
  cloud:
    config:
      server:
        git:
          # ????????? ????? ?? ?????????, ? ???????????,
          # ? ??????? ?????? ??????? ???????????? ? Github
          default-label: master
          # ????? ??????????? Git (??? ???????? ???????????? ??????????)
          uri: https://github.com/alex-sky-cloud/properties-spring-cloud-service-example.git
          # ??? ??????? ??????? ???????, ??????????? ?? ?????????? ???????????
          # "??????" ???????????? ??????????, ? ????????? git
          clone-on-start: true
          # ????????? ???????????, ???? ????? ???????????? ???????????? ???????? ?? ?????????? ???????????
          basedir: file://d:/tmp-spring/git-config
          # login ????????????, ?????????? ???????????
          username: alex-sky-cloud
          # personal access token ?????????? ???????????
          password: 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
server:
  port: 8888

logging:
  pattern:
    # ?????????? ?????? ????? ????????? ??????????? ?????
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'