spring:
  application:
    name: spring-config-server-github
  cloud:
    config:
      server:
        git:
          # Указываем ветку по умолчанию, в репозитории,
          # в котором будете хранить конфигурации в Github
          default-label: master
          # адрес репозитория Git (где хранятся конфигурации приложений)
          uri: https://github.com/alex-sky-cloud/properties-spring-cloud-service-example.git
          # при запуске данного сервера, клонировать из удаленного репозитория
          # "свежие" конфигурации приложений, в локальный git
          clone-on-start: true
          # локальный репозиторий, куда будут клонироватся конфигурации сервисов из удаленного репозитория
          basedir: file://d:/tmp/git-config
          # login пользователя, удаленного репозитория
          username: alex-sky-cloud
          # personal access token удаленного репозитория
          password: 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
server:
  port: 8888

logging:
  pattern:
    # определяем формат более короткого отображение логов
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'



