spring:
  application:
    name: eureka-client
  cloud:
    config:
      uri: http://localhost:8888
  config:
    # этот uri имеет приоритет над значением в spring.cloud.config.uri
    import: configserver:http://localhost:8888

  profiles:
    active: microservice, logging
eureka:

  client:
    healthcheck:
      enabled: true

    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: trace