SERVER_PORT_SERVICE_DISCOVERY: 8081
IP_ADDRESS_SERVICE_DISCOVERY: http://localhost
SERVER_PORT_CLIENT: 0

eureka:
  instance:
    # https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/#changing-the-eureka-instance-id
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    # Значение по умолчанию для обоих этих свойств равно true,
    # что указывает на то, что Eureka client должен извлекать реестр из других экземпляров Eureka,
    # и он должен зарегистрироваться в качестве сервиса на других серверах Eureka
    # если в режиме разработки нет других серверов Eureka, вы устанавливаете для fetch-registry: false,
    # чтобы Eureka не пыталась связаться с другими серверами Eureka.

    # Определяет, будет ли этот клиент пытаться подключиться к серверу (серверам)
    # Eureka для загрузки информации о endpoints других services
    # и, следовательно, иметь возможность подключаться к ним.
    # Клиенты Eureka извлекают информацию реестра с сервера и кэшируют ее локально.
    # После этого клиенты используют эту информацию для поиска других сервисов.
    #  Получать или нет информацию о зарегистрированных клиентах.
    fetch-registry: true
    #  Определяет, регистрируется ли сервис как клиент на Eureka Server, а значит
    # становиться ли доступным для обнаружения.
    register-with-eureka: true
    service-url:
      #Адрес сервера регистрации(eureka-server)
      defaultZone: ${IP_ADDRESS_SERVICE_DISCOVERY}:${SERVER_PORT_SERVICE_DISCOVERY}/eureka
logging:
  pattern:
    # определяем формат более короткого отображение логов
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
server:
  # указав значение 0, это значит, что данные сервис получит случайный порт
  # однако в этом случае, Service Discovery не сможет отобразить порт подключения данного сервиса
  # на своей Admin-панели (dashboard).
  port: ${SERVER_PORT_CLIENT}
spring:
  application:
    name: eureka-client # Id-приложения. Его желательно указывать всегда в микро-сервисных приложениях

