spring:
  application:
    # имя текущего сервиса, это очень нужно для правильного взаимодействия с Spring config server
    #  по этому же имени ищется файл с конфигурацией, для текущего сервиса
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8888

  profiles:
    active: microservice

eureka:

  client:
    healthcheck:
      enabled: true

    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: trace